<?php
	sleep(1);

	$response = [];

	if(isset($_GET["id"])){

		$response = [
			"chapter" => '<h2>Adipisci voluptatem nemo docimus quisquam, quam perferendis quasi similique. Animi, impedit, laboriosam!</h2><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.</p>
				<span class="separator"></span>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.</p>
				<span class="separator"></span>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.</p>
				<span class="separator"></span>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officiis laboriosam culpa perspiciatis sed ipsa expedita alias adipisci, eius accusamus fugiat soluta qui impedit labore praesentium error. Fuga fugiat numquam consequatur?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus voluptatum facere a consequuntur, eaque. Accusantium molestias dolorum laudantium, cupiditate id officiis vitae distinctio tempore quidem nobis necessitatibus. Omnis, autem sunt!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni eos excepturi, iusto provident ullam quo, quia laborum molestias error, nulla perferendis delectus accusantium facilis illum nam vitae porro inventore labore!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo dolorem dolorum, laboriosam magni pariatur, assumenda quaerat reprehenderit aperiam harum iure unde corporis aut in, ullam voluptate possimus eius rerum nesciunt.</p>',
			"prev_link" => "#blank-left",
			"next_link" => "#blank-right"
		];
		echo json_encode($response);
	}

?>